# Generated by Django 4.2 on 2023-04-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bx_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='pub_date',
        ),
    ]
