# Generated by Django 4.2 on 2023-04-20 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bx_app', '0002_remove_answer_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
