# Generated by Django 4.2 on 2023-04-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bx_app', '0003_answer_answer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_identifier',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
