# Generated by Django 4.2 on 2023-04-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bx_app', '0004_question_question_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=20000),
        ),
    ]
